"""Phase 22 RAG reasoning-context boundary."""

from src.agent.rag_context.builder import ContextBuilder
from src.agent.rag_context.claims import (
    ClaimVerifierStatus,
    MaterialClaim,
    MaterialClaimAuthorityClass,
    claim_dependency_map_from_claims,
    normalize_claim_dependency_map,
    normalize_material_claim,
    normalize_material_claims,
    valid_claim_dependency_map,
)
from src.agent.rag_context.metrics import (
    DEFAULT_HALLUCINATION_THRESHOLDS,
    HallucinationCaseResult,
    REQUIRED_HALLUCINATION_METRICS,
    evaluate_hallucination_case,
    threshold_failures,
)
from src.agent.rag_context.routing import VerificationRoute, VerificationRouteDecision, determine_verification_route
from src.agent.rag_context.schemas import (
    CitationMapEntry,
    EvidenceTraceEntry,
    PromptCitation,
    RagContextBudget,
    RagContextBudgetTrace,
    RagContextBuildInput,
    RagContextBundle,
    RagDebugContext,
    RagPromptContext,
    RagSafeContext,
    RagVerifierContext,
)
from src.agent.rag_context.verifier import (
    Level1VerificationResult,
    Level2SupportOutcome,
    Level2VerificationResult,
    MaterialClaimVerificationResult,
    MaterialClaimVerifier,
    SemanticSupportVerifier,
    SemanticVerificationOutcome,
    SemanticVerificationResult,
    SemanticVerifierConfig,
    SemanticVerifierRequest,
    VerificationOutcome,
    should_run_level3_semantic_verification,
)

__all__ = [
    "CitationMapEntry",
    "ClaimVerifierStatus",
    "ContextBuilder",
    "DEFAULT_HALLUCINATION_THRESHOLDS",
    "EvidenceTraceEntry",
    "HallucinationCaseResult",
    "Level1VerificationResult",
    "Level2SupportOutcome",
    "Level2VerificationResult",
    "MaterialClaim",
    "MaterialClaimAuthorityClass",
    "MaterialClaimVerificationResult",
    "MaterialClaimVerifier",
    "PromptCitation",
    "RagContextBudget",
    "RagContextBudgetTrace",
    "RagContextBuildInput",
    "RagContextBundle",
    "RagDebugContext",
    "RagPromptContext",
    "REQUIRED_HALLUCINATION_METRICS",
    "RagSafeContext",
    "RagVerifierContext",
    "SemanticSupportVerifier",
    "SemanticVerificationOutcome",
    "SemanticVerificationResult",
    "SemanticVerifierConfig",
    "SemanticVerifierRequest",
    "VerificationOutcome",
    "VerificationRoute",
    "VerificationRouteDecision",
    "claim_dependency_map_from_claims",
    "determine_verification_route",
    "evaluate_hallucination_case",
    "normalize_claim_dependency_map",
    "normalize_material_claim",
    "normalize_material_claims",
    "should_run_level3_semantic_verification",
    "threshold_failures",
    "valid_claim_dependency_map",
]
