from __future__ import annotations


ACCEPTED_OCR_AVERAGE_CONFIDENCE = 80
REVIEW_NEEDED_OCR_CONFIDENCE_MIN = 55
REVIEW_NEEDED_OCR_CONFIDENCE_MAX = 79
REJECTED_OCR_CONFIDENCE_MAX = 54
OCR_TIMEOUT_SECONDS_PER_PAGE = 15


def test_ocr_confidence_threshold_scaffold_values_are_locked() -> None:
    assert ACCEPTED_OCR_AVERAGE_CONFIDENCE >= 80
    assert REVIEW_NEEDED_OCR_CONFIDENCE_MIN == 55
    assert REVIEW_NEEDED_OCR_CONFIDENCE_MAX == 79
    assert REJECTED_OCR_CONFIDENCE_MAX < 55
    assert OCR_TIMEOUT_SECONDS_PER_PAGE == 15

